/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingRegistration } from "./VotingRegistration";
export * as factories from "./factories";
export { VotingRegistration__factory } from "./factories/VotingRegistration__factory";
